### ISSUE TITLE
Exception raised when data item doesn't exist on disk

### ISSUE THREAD

**Issue by nickpeirson** [bmarini/health_inspector#2]
If a data bag exists in opscode and in the chef repo on disk, but a data bag item doesn't exist, the following exception is raised:

```
/usr/local/rvm/gems/ruby-1.9.2-p290/gems/health_inspector-0.0.4/lib/health_inspector/checklists/data_bag_items.rb:64:in `read': No such file or directory - ./data_bags/aws/rds.json (Errno::ENOENT)
from /usr/local/rvm/gems/ruby-1.9.2-p290/gems/health_inspector-0.0.4/lib/health_inspector/checklists/data_bag_items.rb:64:in `load_item_from_local'
from /usr/local/rvm/gems/ruby-1.9.2-p290/gems/health_inspector-0.0.4/lib/health_inspector/checklists/data_bag_items.rb:33:in `block (2 levels) in items'
from /usr/local/rvm/gems/ruby-1.9.2-p290/gems/health_inspector-0.0.4/lib/health_inspector/checklists/data_bag_items.rb:30:in `tap'
from /usr/local/rvm/gems/ruby-1.9.2-p290/gems/health_inspector-0.0.4/lib/health_inspector/checklists/data_bag_items.rb:30:in `block in items'
from /usr/local/rvm/gems/ruby-1.9.2-p290/gems/health_inspector-0.0.4/lib/health_inspector/checklists/data_bag_items.rb:29:in `map'
from /usr/local/rvm/gems/ruby-1.9.2-p290/gems/health_inspector-0.0.4/lib/health_inspector/checklists/data_bag_items.rb:29:in `items'
...
```

**Comment by bmarini** [comment]
Hey, thanks for posting the bug. I just pushed out a new release that should fix this.

**Comment by nickpeirson** [comment]
Yup, works now.

Thanks
